version: "2.1"

services:

  node-1:
    build:
      context: .
      dockerfile: .mvn/Dockerfile
    networks: [backing-services]
    ports:
    - "8081:8080"
    - "45588"

  node-2:
    build:
      context: .
      dockerfile: .mvn/Dockerfile
    networks: [backing-services]
    ports:
    - "8082:8080"
    - "45588"

networks:
  backing-services:
    driver: bridge
